FROM node:12-alpine
#FROM bitnami/node:12-prod
LABEL maintainer="Zeus Baba 397125+zeusbaba@users.noreply.github.com"

ENV APP_HOME=/usr/src/app
ENV APP_PORT=4048

# optionally if you want to run npm global bin without specifying path
ENV NPM_CONFIG_PREFIX=$APP_HOME/.npm-global
ENV PATH=$PATH:$APP_HOME/.npm-global/bin

RUN mkdir -p $APP_HOME
#RUN chown -R node.node APP_HOME
WORKDIR $APP_HOME

## used to check if service is up
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.4.0/wait ./wait
RUN chmod +x ./wait

RUN npm install -g -s --no-progress yarn
RUN yarn global add serve

# Bundle app build
COPY ../build ./build
COPY serve.json ./build/serve.json
COPY ../static.json ./build/static.json
COPY ../tsconfig.json ./build/tsconfig.json

EXPOSE ${APP_PORT}
CMD ./wait && serve build -l tcp://0.0.0.0:${APP_PORT} -c serve.json
